version: '3.7'
services:
  #############################################################################################
  ###                                 SPLUNK DEV BOX                                        ###
  #############################################################################################
  splunk:
    image: splunk/splunk:8.0.2.1
    environment:
      - SPLUNK_PASSWORD=${SPLUNK_PASSWORD}
      - SPLUNK_START_ARGS=--accept-license
    ports:
      - "8000:8000"
    networks:
      - rsbc-df-vips

  #############################################################################################
  ###                                 SPLUNK INIT                                           ###
  #############################################################################################
  splunk-init:
    build:
      context: ./splunk
    environment:
      - SPLUNK_PASSWORD=${SPLUNK_PASSWORD}
      - SPLUNK_TOKEN=${SPLUNK_TOKEN}
    networks:
      - rsbc-df-vips

  #############################################################################################
  ###                                 POSTGRESQL                                            ###
  #############################################################################################
  postgresql:
    image: postgres:9.5
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=${POSTGRESQL_PASSWORD}
      - POSTGRES_DB=sonar
    networks:
      - rsbc-df-vips
    volumes:
      - postgresql-data:/var/lib/pgsql/data

  #############################################################################################
  ###                                 SONARQUBE                                             ###
  #############################################################################################
  sonarqube:
    image: sonarqube:8.2-community
    environment:
      - SONARQUBE_JDBC_PASSWORD=${POSTGRESQL_PASSWORD}
      - SONARQUBE_JDBC_URL=jdbc:postgresql://postgresql/sonar
      - SONARQUBE_JDBC_USERNAME=sonar
      - SONAR_FORCEAUTHENTICATION=true
    ports:
      - "9000:9000"
    networks:
      - rsbc-df-vips
    volumes:
      - sonar-data:/opt/sonarqube/data
      - sonar-logs:/opt/sonarqube/logs
      - sonar-temp:/opt/sonarqube/temp
      - sonar-plugins:/opt/sonarqube/extensions/plugins
    restart: always

  #############################################################################################
  ###                                 SONARQUBE INIT                                        ###
  #############################################################################################
  sonarqube-init:
    build:
      context: ./sonarqube
    environment:
      - PGPASSWORD=${POSTGRESQL_PASSWORD}
      - SONAR_TOKEN=${SONAR_TOKEN}
      - SONAR_PROJECT_KEY=${SONAR_PROJECT_KEY}
    networks:
      - rsbc-df-vips
    volumes:
      - sonar-plugins:/opt/plugins

  #############################################################################################
  ###                               Digital forms API                                       ###
  #############################################################################################
  digitalforms-api:
    build:
      context: ./digitalforms-api
    environment:
      - DIGITALFORMS_BASICAUTH_PASSWORD=${DIGITALFORMS_BASICAUTH_PASSWORD}
      - DIGITALFORMS_BASICAUTH_USER=${DIGITALFORMS_BASICAUTH_USER}
      - DIGITALFORMS_SWAGGER_ENABLED=${DIGITALFORMS_SWAGGER_ENABLED}
      - DIGITALFORMS_VIPSORDS_BASEPATH=${DIGITALFORMS_VIPSORDS_BASEPATH}
      - DIGITALFORMS_VIPSORDS_USER=${DIGITALFORMS_VIPSORDS_USER}
      - DIGITALFORMS_VIPSORDS_PASSWORD=${DIGITALFORMS_VIPSORDS_PASSWORD}
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
      - SPLUNK_TOKEN=${SPLUNK_TOKEN}
      - SPLUNK_URL=${SPLUNK_URL}
      - SONAR_TOKEN=${SONAR_TOKEN}
      - SONAR_URL=http://sonarqube:9000
      - SONAR_PROJECT_KEY=${SONAR_PROJECT_KEY}
    ports:
      - "8082:8082"
    volumes:
      - maven-repository:/root/.m2/repository
    networks:
      - rsbc-df-vips

volumes:
  maven-repository:
  postgresql-data:
  sonar-data:
  sonar-logs:
  sonar-temp:
  sonar-plugins:

networks:
  rsbc-df-vips:
    driver: "bridge"
