version: '3.7'
services:
  #############################################################################################
  ###                                 SPLUNK DEV BOX                                        ###
  #############################################################################################
  splunk:
    image: splunk/splunk:8.0.2.1
    environment:
      - SPLUNK_PASSWORD=${SPLUNK_PASSWORD}
      - SPLUNK_START_ARGS=--accept-license
    ports:
      - "8000:8000"
    networks:
      - rsbc-df-vips

  #############################################################################################
  ###                                 SPLUNK INIT                                           ###
  #############################################################################################
  splunk-init:
    build:
      context: ./splunk/hec_setup
    environment:
      - SPLUNK_PASSWORD=${SPLUNK_PASSWORD}
      - SPLUNK_TOKEN=${SPLUNK_TOKEN}
    networks:
      - rsbc-df-vips

  #############################################################################################
  ###                               Digital forms API                                       ###
  #############################################################################################
  digitalforms-api:
    build:
      context: ./digitalforms-api
    environment:
      - DIGITALFORMS_BASICAUTH_PASSWORD=${DIGITALFORMS_BASICAUTH_PASSWORD}
      - DIGITALFORMS_BASICAUTH_USER=${DIGITALFORMS_BASICAUTH_USER}
      - DIGITALFORMS_SWAGGER_ENABLED=${DIGITALFORMS_SWAGGER_ENABLED}
      - DIGITALFORMS_VIPSORDS_BASEPATH=${DIGITALFORMS_VIPSORDS_BASEPATH}
      - DIGITALFORMS_VIPSORDS_USER=${DIGITALFORMS_VIPSORDS_USER}
      - DIGITALFORMS_VIPSORDS_PASSWORD=${DIGITALFORMS_VIPSORDS_PASSWORD}
    ports:
      - "8082:8082"
    volumes:
      - maven-repository:/root/.m2/repository
    networks:
      - rsbc-df-vips

volumes:
  maven-repository:

networks:
  rsbc-df-vips:
    driver: "bridge"
