apiVersion: v1
kind: Template
labels:
  template: digitalforms-api-scans-pipeline-template
message: |-
  A Jenkins server must be instantiated in this project to manage
  the Pipeline BuildConfig created by this template. You will be able to log in to
  it using your OpenShift user credentials.
metadata:
  annotations:
    openshift.io/display-name: digitalforms-api scans pipeline template
    description: |-
      This is a template for digitalforms-api scans pipeline.
    iconClass: icon-jenkins
    tags: instant-app,jenkins
  name: digitalforms-api-scans-pipeline-template
parameters:
- description: The OpenShift Namespace prefix.
  displayName: Namespace Prefix (Prefix for each namespace ie prefix-tools, prefix-dev etc)
  name: namespacePrefix
  required: true
  value:
- description: Github trigger secret. A difficult to guess string encoded as part of the webhook URL. Not encrypted.
  displayName: GitHub Webhook Secret (Generated if empty)
  from: '[a-zA-Z0-9]{40}'
  generate: expression
  name: gitSecret
- description: API definition, url pointing to swagger.json
  displayName: API definition URL
  name: apiDefinitionUrl
  required: true
  value: set.api.swagger.json
- description: Sonarqube Raw Token
  displayName: Sonarqube Token
  name: sonartoken
  required: true
  value:
objects:
- apiVersion: build.openshift.io/v1
  kind: BuildConfig
  metadata:
    labels:
      application: digitalforms-api
      template: master-build-pipeline
    name: digitalforms-api-scans-pipeline
    namespace: ${namespacePrefix}-tools
  spec:
    failedBuildsHistoryLimit: 5
    nodeSelector: {}
    output: {}
    postCommit: {}
    resources: {}
    runPolicy: Serial
    source:
      git:
        ref: master
        uri: https://github.com/bcgov/jag-rsbc-digital-forms-vips-integration
      type: Git
    strategy:
      jenkinsPipelineStrategy:
        env:
        - name: APP_NAME
          value: digitalforms-api
        - name: API_DEFINITION_URL
          value: ${apiDefinitionUrl}
        - name: LIFECYCLE_WEBHOOK
        - name: GIT_SOURCE_URL
          value: https://github.com/bcgov/jag-rsbc-digital-forms-vips-integration
        - name: GIT_SOURCE_REF
          value: master
        - name: GIT_CREDENTIALS_ID
          value:
        - name: SONAR_TOKEN
          value: ${sonartoken}
        - name: SONAR_PROJECT_KEY
          value: digitalforms_api
        - name: SONAR_URL
          value: http://sonarqube:9000
        - name: SONAR_COMMAND
        - name: SONAR_ENABLED
          value: "true"
        - name: TOOLS_NAMESPACE
          value: ${namespacePrefix}-tools
        - name: DEV_NAMESPACE
          value: ${namespacePrefix}-dev
        - name: TEST_NAMESPACE
          value: ${namespacePrefix}-test
        - name: PROD_NAMESPACE
          value: ${namespacePrefix}-prod
        jenkinsfile: |-
          try {
            // The API format; either openapi or soap
            def API_FORMAT = 'openapi'
            // The name  of the ZAP report
            def ZAP_REPORT_NAME = "zap-report.xml"
            // The location of the ZAP reports
            def ZAP_REPORT_PATH = "/zap/wrk/${ZAP_REPORT_NAME}"
            // The name of the "stash" containing the ZAP report
            def ZAP_REPORT_STASH = "zap-report"

            def ZAP_ENABLED = "false"
            def SONAR_ENABLED = "false"

            if ("${ZAP_ENABLED}"!="false") {
              node("zap") {
                stage('ZAP Security Scan') {
                  timeout(time: 60, unit: 'MINUTES') {

                    dir('zap') {
                      git url: "${GIT_SOURCE_URL}", branch: "${GIT_SOURCE_REF}", credentialsId: "${GIT_CREDENTIALS_ID}"
                      def retVal = sh (
                        returnStatus: true,
                        script: """
                          mkdir -p /zap/wrk/
                          mv zap/options.conf /zap/wrk/options.conf
                          mv zap/default.context /zap/wrk/default.context

                          cp -r /var/lib/jenkins/.ZAP/policies /var/lib/jenkins/

                          zap-api-scan.py -t "${API_DEFINITION_URL}" \
                            -f openapi \
                            -d \
                            -x ${ZAP_REPORT_NAME} \
                            -z "-configfile /zap/wrk/options.conf -d /var/lib/jenkins" \
                            -n /zap/wrk/default.context
                        """
                      )
                      echo "Return value is: ${retVal}"

                      // Copy the ZAP report into the Jenkins working directory so the Jenkins tools can access it.
                      sh (
                        returnStdout: true,
                        script: "mkdir -p ./wrk/ && cp ${ZAP_REPORT_PATH} ./wrk/"
                      )
                    }

                    // Stash the ZAP report for publishing in a different stage (which will run on a different pod).
                    echo "Stash the report for the publishing stage ..."
                    stash name: "${ZAP_REPORT_STASH}", includes: "zap/wrk/*.xml"
                  }
                }
              }
            }

            if ("${SONAR_ENABLED}"!="false") {
              node("maven35") {
                stage("Sonar Scan") {
                  timeout(time: 10, unit: 'MINUTES') {

                    dir("${APP_NAME}") {
                      git url: "${GIT_SOURCE_URL}", branch: "${GIT_SOURCE_REF}", credentialsId: "${GIT_CREDENTIALS_ID}"
                      env.GIT_COMMIT = getCommit()

                      echo "Preparing the report for the publishing ..."
                      unstash name: "${ZAP_REPORT_STASH}"

                      def retVal = sh (
                        returnStatus: true,
                        script: """
                          mvn sonar:sonar \
                            -Dsonar.projectKey=${SONAR_PROJECT_KEY} \
                            -Dsonar.host.url=${SONAR_URL} \
                            -Dsonar.login=${SONAR_TOKEN} \
                            -Dsonar.zaproxy.reportPath=${WORKSPACE}/${APP_NAME}${ZAP_REPORT_PATH}
                        """
                      )
                      echo "Return value is: ${retVal}"

                    }
                  }
                }
              }
            }
          } catch (err) {
            echo "in catch block"

            currentBuild.result = 'FAILURE'
            env.ERR = "${err}"
            node {
                sh "curl -XPOST '${LIFECYCLE_WEBHOOK}' -H 'Content-type: application/json' --data '{\"username\":\"The Pipe Lion\",\"icon_emoji\":\":lion_face:\",\"text\": \"${APP_NAME} Pipeline Failure - ${ERR}\"}'"
            }
            echo "Caught: ${err}"
            throw err
          }

          String getCommit() {
              return sh(script: 'git rev-parse HEAD', returnStdout: true)?.trim()
          }
      type: JenkinsPipeline
    successfulBuildsHistoryLimit: 5
    triggers:
    - type: ConfigChange
    - github:
        secret: ${gitSecret}
      type: GitHub
